### ISSUE TITLE
Config says No Plugim

### ISSUE THREAD

**Issue by donavanbecker** [homebridge-plugins/homebridge-sharkiq#1]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
No plugin was found for the platform
"SharkIPlugin" in your config.json. Please make sure the corresp onding plugin is installed correctly.
```

**Plugin Config:**

```json
{
"vacuums": [],
"email": "email@email.com",
"password": "12345678",
"platform": "SharkIQPlugin"
}

```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by Bubba8291** [comment]
Platform is supposed to be `SharkIQ`
Name is supposed to be `SharkIQPlugin`

Edit: There's also a typo in your config according to the log

**Comment by donavanbecker** [comment]
this is call coming from your config.schema.json. I will submit a PR

**Comment by Bubba8291** [comment]
Merged and pushed to npmjs.com.
