### ISSUE TITLE
None of the DSNs provided matched the vacuum(s) on your account (but it's on my account)

### ISSUE THREAD

**Issue by WPTK** [homebridge-plugins/homebridge-sharkiq#13]
**Describe The Bug:**
The plugin says there is no such DSN on my account, but the DSN is directly copy+pasted from the app

**To Reproduce:**
Initial setup, enter DSN. Confirm DSN is correct in app. Copy and paste directly from in-app screenshot. Hand type the DSN. 

**Expected behavior:**
Expected it to recognize it

**Logs:**
```
[12/29/2023, 10:11:06 AM] [SharkIQ] None of the DSNs provided matched the vacuum(s) on your account.
[12/29/2023, 10:11:06 AM] [SharkIQ] If you recently updated, vacuums are obtained by the device serial number (DSN) instead of the vacuum serial number.
```

**Plugin Config:**

```
{
    "bridge": {
        "name": "Homebridge REDACTED",
        "username": "REDACTED",
        "port": 51144,
        "pin": "REDACT",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "devicesUseDiscoveryPort": false,
            "platform": "TplinkSmarthome"
        },
        {
            "name": "SharkIQ",
            "email": "REDACTED@REDACTED.com",
            "password": "REDACTED",
            "vacuums": [
                "REDACTED"
            ],
            "europe": false,
            "invertDockedStatus": false,
            "dockedUpdateInterval": 5000,
            "platform": "SharkIQ"
        }
    ]
}
```

**Environment:**

* **Plugin Version**:  1.1.2
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 18.13.0
* **NPM Version**: whatever ships with homebridge docker container
* **Operating System**: Windows 10 (homebridge-provided Hyper-V image)

**Comment by WPTK** [comment]
Fixed the issue. Turns out the font they use in their app doesn't help with OCR from iOS and is difficult to read. 

For future readers: If your DSN starts with ACOOO, it's probably AC000. Yes, even if the next zero you see looks like a zero.

**Comment by Bubba8291** [comment]
Glad you were able to figure it out. Let me know if you have any other issues.
