### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mj261** [homebridge-plugins/homebridge-sharkiq#14]
**Describe The Bug:**
When initially logging in, the plugin returns "Login information must be present in config", even when a valid email, password, and serial are provided

**To Reproduce:**
1. Download plugin
2. Use config provided:
{
    "name": "SharkIQ",
    "platform": "SharkIQ",
    "email": "****************",
    "password": "**************",
    "vacuums": [
        "***********"
    ],
    "europe": false,
    "invertDockedStatus": false,
    "dockedUpdateInterval": 5000
}

**Expected behavior:**
Login and showing devices

**Logs:**

2/11/2024, 10:44:30 PMSharkiq Bridge starting
2/11/2024, 10:44:34 PMSharkiq BridgeLoaded plugin 'homebridge-sharkiq'
2/11/2024, 10:44:34 PMSharkiq BridgeLoading 2 platforms...
2/11/2024, 10:44:34 PMSharkiq BridgeSharkIQERRORLogin information must be present in config
2/11/2024, 10:44:34 PMSharkiq BridgeBridge is running on port 51876.

**Plugin Config:**

shown above

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.1.2
* **Homebridge Version**: 1.7.0 running on Hoobs 4.3.1
* **Node.js Version**: 16.20.2
* **NPM Version**: 8.19.4
* **Operating System**: Hoobs

**Comment by Bubba8291** [comment]
I am unable to reproduce. The thing I can think of off the top of my head: Is your SharkIQ config under `platforms` and not `accessories`?

Edit: This error does not mean the login is incorrect; it means that either the `email` and/or `password` field is not present in the config.

**Comment by mj261** [comment]
I was able to find a resolution.  The native Hoobs JSON editor does not allow you to see the entire file and the plugin does not seem to be developed with Hoobs compatibility.  To work with Hoobs, you need to click the gear in the bottom left, go to "Advanced", Click "Sharkiq", and add the config manually.

**Comment by Bubba8291** [comment]
Glad you figured it out.
