### ISSUE TITLE
Still Unable to Load Plugin 

### ISSUE THREAD

**Issue by tjridge** [homebridge-plugins/homebridge-sharkiq#20]
**Describe The Bug:**
Unable to get account linked. 

**To Reproduce:**

**Expected behavior:**

**Logs:**
```
[20/08/2024, 16:29:09] [SharkIQ] API Error: Unauthorized
[20/08/2024, 16:29:09] [SharkIQ] SharkIQ will not continue. If the issue persists, open an issue.
[20/08/2024, 16:29:09] [SharkIQ] API Error: Unauthorized
[20/08/2024, 16:29:09] [SharkIQ] Attempting to refresh access token.
[20/08/2024, 16:29:09] [SharkIQ] API Error: Unable to refresh auth token. Status Code 401
[20/08/2024, 16:29:09] [SharkIQ] Message: Your refresh token is not found
[20/08/2024, 16:29:09] [SharkIQ] Refreshing access token failed. Please check your auth file and recreate it if needed.
[20/08/2024, 16:29:09] [SharkIQ] SharkIQ will not continue. If the issue persists, open an issue.
[20/08/2024, 16:29:09] [SharkIQ] None of the DSNs provided matched the vacuum(s) on your account.
```

**Plugin Config:**

```json
{
    "name": "SharkIQ",
    "vacuums": [
        "ACXXXXXXXXXXXXX",
        "ACXXXXXXXXXXXXX"
    ],
    "europe": false,
    "invertDockedStatus": false,
    "dockedUpdateInterval": 5000,
    "_bridge": {
        "username": "0E:EF:XX:XX:XX:XX",
        "port": 30803
    },
    "platform": "SharkIQ"
}
```
**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by Bubba8291** [comment]
@tjridge Was the plugin logged in using the new method at first?

**Comment by tjridge** [comment]
Yes, but I got the same errors. Now, the link to the page will not load in the terminal. I just get the above error. I've tried deleting the plugin and restoring Homebridge from a previous backup with no luck.

**Comment by Bubba8291** [comment]
> Yes, but I got the same errors. Now, the link to the page will not load in the terminal. I just get the above error. I've tried deleting the plugin and restoring Homebridge from a previous backup with no luck.

@tjridge Ah. You have to remove the `.sharkiq.json` file in order for the link to reappear to reauthenticate. I will make that a warning message in the next update.

As for the access token refresh failing, I will have to look into it. I am still not sure how long or if the refresh token expires.

**Comment by tjridge** [comment]
How would one remove the .sharkiq.json file?😬

**Comment by Bubba8291** [comment]
> How would one remove the .sharkiq.json file?😬

@tjridge I edited your first comment. Can you add the info in the environment section?

**Comment by tjridge** [comment]
Environment:

Plugin Version: 1.2.0
Homebridge Version: 1.8.4
Node.js Version: v20.17.0
NPM Version: ?
Operating System: Debian GNU/Linux Bookworm (12)

**Comment by Bubba8291** [comment]
@tjridge Can you join the Homebridge Discord server and message in the #sharkiq channel to help further?

On the next update, I will have the error message include the file path.

**Comment by Bubba8291** [comment]
@tjridge Can you update to v1.2.2? The package will log the auth file location, in which you can navigation to that location and remove it.

**Comment by thatpaulallen** [comment]
I'm having the exact same issue. How do I navigate to /var/lib/homebridge/.sharkiq.json ?

I'm running raspbian

**Comment by Bubba8291** [comment]
@thatpaulallen Run `rm /var/lib/homebridge/.sharkiq.json` in the pi terminal, then restart.

**Comment by thatpaulallen** [comment]
Worked perfectly. Thank you

**Comment by Bubba8291** [comment]
Closing. If anyone has any support questions with setting up the plugin, please join the [Homebridge Discord Server](https://discord.gg/kqNCe2D) and message in `#sharkiq`.
