### ISSUE TITLE
Homebridge 2.0 Compatibility

### ISSUE THREAD

**Issue by PaulAtkinsonPDX** [homebridge-plugins/homebridge-sharkiq#22]
Hey,

Soon Homebridge 2.0 will be released which will have some breaking changes to plugins.
Could you please check if this plugin is impacted and make it work with 2.0?

[Homebridge 2.0](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0)

**Comment by Bubba8291** [comment]
@PaulAtkinsonPDX will Homebridge 2.0 include native robo vacuum support?

**Comment by Bubba8291** [comment]
@PaulAtkinsonPDX Added in `v1.3.1`
