### ISSUE TITLE
How do I get a Sharkiq authorization code?

### ISSUE THREAD

**Issue by Wsm204** [homebridge-plugins/homebridge-sharkiq#23]
**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by donavanbecker** [comment]
By typing in your username and password in the config.

**Comment by idle0095** [comment]
That does not work for me.  It wants the oauth code.

**Comment by Bubba8291** [comment]
@idle0095 Instructions are in the README.
