### ISSUE TITLE
Using username and password I get error [SharkIQ] Error with login.

### ISSUE THREAD

**Issue by idle0095** [homebridge-plugins/homebridge-sharkiq#26]
**Describe Your Problem:**
running on a raspberry pi 4.  I use my shark username and password and I get [SharkIQ] Error with login.
I cannot get the other way to work either.  

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by Bubba8291** [comment]
Pi 4 requires manual OAuth login. Leave the email and password field blank and follow the instructions from the readme

#25
