### ISSUE TITLE
Failed login after update and complete re-install

### ISSUE THREAD

**Issue by kinetic-github** [homebridge-plugins/homebridge-sharkiq#27]
**Describe The Bug:**
Plugin will not load and bring in devices

**To Reproduce:**
updated to 1.3.1 to begin error.  Even deleted and installed from scratch

**Expected behavior:**
Expected to have access to both Shark IQ devices

**Logs:**

[28/10/2024, 10:52:16] [SharkIQ] Launched child bridge with PID 18650
[28/10/2024, 10:52:18] [SharkIQ] Loaded homebridge-sharkiq v1.3.1 child bridge successfully
[28/10/2024, 10:52:19] Homebridge v1.8.5 (HAP v0.12.3) (SharkIQ) is running on port 35768.
[28/10/2024, 10:52:19] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[28/10/2024, 10:52:19] [SharkIQ] Error with login.
[28/10/2024, 10:52:19] [SharkIQ] Error: Error: Failed to launch the browser process!
/home/trataiczak/.cache/puppeteer/chrome/linux-129.0.6668.70/chrome-linux64/chrome: 1: Syntax error: Unterminated quoted string

TROUBLESHOOTING: https://pptr.dev/troubleshooting

**Plugin Config:**

{
    "name": "SharkIQ",
    "email": "terry@theratsnest.org",
    "password": "xxxxxxxx",
    "vacuums": [
        "AC000W028689382",
        "AC000W030184930"
    ],
    "europe": false,
    "invertDockedStatus": true,
    "dockedUpdateInterval": 30000,
    "platform": "SharkIQ",
    "_bridge": {
        "username": "0E:43:CB:11:9A:8C",
        "port": 35768
    }
}

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.3.1
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 20.18.0
* **NPM Version**: 
* **Operating System**: Raspbian GNU/Linux Bullseye (11)

**Comment by Bubba8291** [comment]
Remove the email and password in your homebridge config and restart homebridge. This is a known issue with arm64 devices.
