### ISSUE TITLE
Shows up as contact sensor only

### ISSUE THREAD

**Issue by BENJAMINZSIMON** [homebridge-plugins/homebridge-sharkiq#32]
**Describe The Bug:**
only shows vacuum as contact sensor no other controls at all

**To Reproduce:**
used authcode to connect

**Expected behavior:**
controls expected
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
v20.10.0
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by BENJAMINZSIMON** [comment]
Plugin Version: 1.3.2
Homebridge Version: 1.8.5
Node.js Version: 20.10.0
UI: 4.63.0
Operating System: Raspbian GNU/Linux Bullseye (11) Mac

**Comment by Bubba8291** [comment]
@BENJAMINZSIMON I am guessing you fixed the issue?

**Comment by BENJAMINZSIMON** [comment]
thank you yes it just took some time to populate :)
