### ISSUE TITLE
SharqIQ Fails to start when Homebridge is installed on DSM

### ISSUE THREAD

**Issue by Romeo1984** [homebridge-plugins/homebridge-sharkiq#33]
**Describe The Bug:**
SharkIQ Plugin fails to launch Chromium due to a missing library when Homebridge is installed on DSM 

**To Reproduce:**
1. Install Homebridge on DSM (x86 Arch).
2. Install and configure the SharqIQ plugin.
3. Restart Homebridge
4. Observe the error in the logs.

**Expected behavior:**
I expect to see the login URL like the ReadMe page states. 

**Logs:**

[12/3/2024, 1:17:37 PM] [SharkIQ] If you received the error Syntax error: Unterminated quoted string, please use the OAuth code login method. This is a known issue with arm64 devices like Raspberry Pi.
[12/3/2024, 1:17:37 PM] [SharkIQ] To login using the OAuth code method, please remove the email and password from your Homebridge configuration and restart Homebridge.
[12/3/2024, 1:17:37 PM] [SharkIQ] Error with login.
[12/3/2024, 1:17:37 PM] [SharkIQ] Error: Error: Failed to launch the browser process!
/var/packages/homebridge/home/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

**Plugin Config:**

```json
{
    "name": "SharkIQ",
    "email": "m******i@gmail.com",
    "password": "*****************",
    "vacuums": [
        "AC000W0226********"
    ],
    "europe": false,
    "invertDockedStatus": false,
    "dockedUpdateInterval": 30000,
    "platform": "SharkIQ",
    "_bridge": {
        "username": "0E:0B:58:0A:**:**",
        "port": 40080
    }
}
```

**Screenshots:**
None

**Environment:**
OS | Synology DSM
DS720Plus2
homebridge
 
/volume1/@appstore/Node.js_v20/usr/local/bin
/volume1/homebridge
/volume1/homebridge/config.json
/volume1/homebridge/node_modules
GMT-0700

* **Plugin Version**: 1.3.2
* **Homebridge Version**:  1.8.5
* **Node.js Version**: 20.9.0
* **NPM Version**: 10.1.0
* **Operating System**: DSM

**Comment by Bubba8291** [comment]
@Romeo1984 Check #24

**Comment by Romeo1984** [comment]
-MarkSent from my iPhoneOn Dec 17, 2024, at 1:09 PM, Bubba8291 ***@***.***> wrote:Why was this closed? Most of the commands in #24 can’t be run on DSM. Please let me trouble shoot before closing. ﻿
@Romeo1984 Check #24

**Comment by Bubba8291** [comment]
@Romeo1984 It looks like your DSM doesn't have libatk installed, which is a system package.

I do not have a Synology, but if there isn't a way to manually add that package (through a web ui or a terminal interface), try to login with the OAuth login

**Comment by Romeo1984** [comment]
@Bubba8291 homebridge-sharkiq ***@***.***>  I
already looked for it. It is not available for DSM to install.

**Comment by Romeo1984** [comment]
@Bubba8291 I was successful in getting OAuth working. That needs to be the solution if Homebridge is installed on any device that can't use apt to update packages. Thanks.

**Comment by Bubba8291** [comment]
@Romeo1984 Awesome! Glad to hear it is working.

I am not sure which range of distros do not come with the required package for puppeteer by default. If there was an efficient way to, I would add it.

For now, I could add more clear error logs
